CREATE TABLE products (
    id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255),
    details VARCHAR(255),
    PRIMARY KEY(id)
);

-- CREATE TABLE images (
--     id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
--     img_url VARCHAR(255),
--     PRIMARY KEY(id) 
-- );

CREATE TABLE product_images (
    id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    product_id INT NOT NULL,
    img_url VARCHAR(255),
    PRIMARY KEY(id)
);

\copy products (id, name, details) FROM './csv-generator/products.csv' DELIMITER ',';

-- COPY images (id, img_url)
-- FROM './images.csv' DELIMITER ',';

\copy product_images (id, product_id, img_url) FROM './csv-generator/product_images.csv' DELIMITER ',';